# Generated by Django 6.1 on 2026-08-13 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.CharField(max_length=512, verbose_name='Valeur de la cible (URL, IP, Domaine)')),
                ('type', models.CharField(choices=[('URL', 'URL Web'), ('DOMAINE', 'Nom de domaine'), ('ADRESSE_IP', 'Adresse IP'), ('API_REST', 'API REST'), ('API_GRAPHQL', 'API GraphQL')], default='URL', max_length=20, verbose_name='Type de cible')),
                ('environnement', models.CharField(choices=[('DEVELOPPEMENT', 'Développement'), ('TEST', 'Test / QA'), ('PREPRODUCTION', 'Pré-production'), ('PRODUCTION', 'Production'), ('LABORATOIRE', 'Laboratoire de sécurité')], default='TEST', max_length=20, verbose_name='Environnement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'autorisation"), ('AUTORISEE', 'Autorisée'), ('REFUSEE', 'Refusée'), ('SUSPENDUE', 'Suspendue'), ('EXPIREE', 'Expirée')], default='EN_ATTENTE', max_length=20, verbose_name="Statut d'autorisation")),
                ('dateAjout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Cible',
                'verbose_name_plural': 'Cibles',
                'ordering': ['-dateAjout'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('organisation', models.CharField(max_length=255, verbose_name='Organisation')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('dateArchivage', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='AutorisationCible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateDebut', models.DateField(verbose_name='Date de début')),
                ('dateFin', models.DateField(verbose_name='Date de fin')),
                ('preuve', models.CharField(max_length=512, verbose_name="Preuve d'autorisation (Document / Ref)")),
                ('testsActifsAutorises', models.BooleanField(default=False, verbose_name='Tests actifs autorisés (Scans destructifs)')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaires & Scope')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to='projects.cible', verbose_name='Cible')),
            ],
            options={
                'verbose_name': 'Autorisation de Cible',
                'verbose_name_plural': 'Autorisations de Cibles',
                'ordering': ['-dateDebut'],
            },
        ),
        migrations.AddField(
            model_name='cible',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibles', to='projects.projet', verbose_name='Projet'),
        ),
    ]
