# Generated by Django 6.1 on 2026-08-15 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la vulnérabilité')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('gravite', models.CharField(choices=[('CRITIQUE', 'Critique (CVSS 9.0 - 10.0)'), ('ELEVEE', 'Élevée (CVSS 7.0 - 8.9)'), ('MOYENNE', 'Moyenne (CVSS 4.0 - 6.9)'), ('FAIBLE', 'Faible (CVSS 0.1 - 3.9)'), ('INFORMATION', 'Information (CVSS 0.0)')], default='MOYENNE', max_length=20, verbose_name='Gravité / Sévérité')),
                ('confiance', models.FloatField(default=100.0, verbose_name='Niveau de confiance (0 à 100%)')),
                ('scoreCVSS', models.FloatField(default=5.0, verbose_name='Score CVSS (0.0 à 10.0)')),
                ('codeCWE', models.CharField(blank=True, default='', max_length=50, verbose_name='Code CWE (ex: CWE-89)')),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('A_VERIFIER', 'À vérifier'), ('CONFIRMEE', 'Confirmée'), ('FAUX_POSITIF', 'Faux positif'), ('CORRECTION_EN_COURS', 'Correction en cours'), ('CORRIGEE', 'Corrigée'), ('RISQUE_ACCEPTE', 'Risque accepté')], default='NOUVELLE', max_length=30, verbose_name='Statut de la vulnérabilité')),
                ('dateDetection', models.DateTimeField(auto_now_add=True, verbose_name='Date de détection')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilites', to='audits.audit', verbose_name='Audit associé')),
            ],
            options={
                'verbose_name': 'Vulnérabilité',
                'verbose_name_plural': 'Vulnérabilités',
                'ordering': ['-scoreCVSS', '-dateDetection'],
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Description du correctif proposé')),
                ('priorite', models.CharField(choices=[('CRITIQUE', 'Critique (CVSS 9.0 - 10.0)'), ('ELEVEE', 'Élevée (CVSS 7.0 - 8.9)'), ('MOYENNE', 'Moyenne (CVSS 4.0 - 6.9)'), ('FAIBLE', 'Faible (CVSS 0.1 - 3.9)'), ('INFORMATION', 'Information (CVSS 0.0)')], default='MOYENNE', max_length=20, verbose_name="Priorité d'application")),
                ('composantConcerne', models.CharField(blank=True, default='', max_length=255, verbose_name='Composant concerné')),
                ('methodeValidation', models.TextField(blank=True, default='', verbose_name='Méthode de validation du patch')),
                ('vulnerabilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='vulns.vulnerabilite', verbose_name='Vulnérabilité associée')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
            },
        ),
        migrations.CreateModel(
            name='Preuve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='HTTP_REQUEST', max_length=50, verbose_name='Type de preuve (ex: HTTP, Payload)')),
                ('contenu', models.TextField(verbose_name='Contenu de la preuve / PoC')),
                ('fichier', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemin du fichier / Capture')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('vulnerabilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='vulns.vulnerabilite', verbose_name='Vulnérabilité associée')),
            ],
            options={
                'verbose_name': 'Preuve (PoC)',
                'verbose_name_plural': 'Preuves (PoC)',
                'ordering': ['-dateCreation'],
            },
        ),
    ]
