# Generated by Django 6.1 on 2026-08-15 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatSSL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet (Subject / CN)')),
                ('emetteur', models.CharField(max_length=255, verbose_name='Émetteur (Issuer)')),
                ('dateDebut', models.DateField(verbose_name="Date d'émission (Not Before)")),
                ('dateExpiration', models.DateField(verbose_name="Date d'expiration (Not After)")),
                ('valide', models.BooleanField(default=True, verbose_name='Est valide')),
                ('protocole', models.CharField(default='TLSv1.3', max_length=50, verbose_name='Protocole SSL/TLS')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_ssl', to='audits.audit', verbose_name='Audit associé')),
            ],
            options={
                'verbose_name': 'Certificat SSL/TLS',
                'verbose_name_plural': 'Certificats SSL/TLS',
                'ordering': ['-dateExpiration'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetecte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port', models.IntegerField(verbose_name='Port réseau')),
                ('protocole', models.CharField(default='tcp', max_length=20, verbose_name='Protocole (tcp/udp)')),
                ('service', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('version', models.CharField(blank=True, default='', max_length=100, verbose_name='Version du service')),
                ('etat', models.CharField(default='open', max_length=50, verbose_name='État du port (open, closed, filtered)')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='audits.audit', verbose_name='Audit associé')),
            ],
            options={
                'verbose_name': 'Service Détecté',
                'verbose_name_plural': 'Services Détectés',
                'ordering': ['port'],
            },
        ),
        migrations.CreateModel(
            name='TechnologieDetectee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la technologie')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='Version')),
                ('categorie', models.CharField(blank=True, default='', max_length=100, verbose_name='Catégorie')),
                ('niveauConfiance', models.FloatField(default=100.0, verbose_name='Niveau de confiance (0 à 100%)')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='audits.audit', verbose_name='Audit associé')),
            ],
            options={
                'verbose_name': 'Technologie Détectée',
                'verbose_name_plural': 'Technologies Détectées',
                'ordering': ['nom'],
            },
        ),
    ]
