# Generated by Django 6.1 on 2026-08-15 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LEGER', 'Léger (Reconnaissance rapide)'), ('STANDARD', 'Standard (OWASP Top 10)'), ('APPROFONDI', 'Approfondi (Pentest complet)'), ('API', 'API REST & GraphQL'), ('SSL_TLS', 'Analyse SSL / TLS & Chiffrement'), ('CONFIGURATION', 'Audit de Configuration & Headers')], default='STANDARD', max_length=30, verbose_name="Type d'audit")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PLANIFICATION', 'Planification'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('PARTIEL', 'Terminé partiellement'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=30, verbose_name="Statut de l'audit")),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('dateDebut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('dateFin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('scoreSecurite', models.FloatField(default=0.0, verbose_name='Score de sécurité (0 à 100)')),
                ('progression', models.IntegerField(default=0, verbose_name='Progression (0 à 100%)')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='projects.cible', verbose_name='Cible')),
                ('lancePar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_lances', to=settings.AUTH_USER_MODEL, verbose_name='Lancé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Audit de Sécurité',
                'verbose_name_plural': 'Audits de Sécurité',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='PlanAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description du plan')),
                ('dateGeneration', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='audits.audit', verbose_name='Audit')),
            ],
            options={
                'verbose_name': "Plan d'Audit",
                'verbose_name_plural': "Plans d'Audit",
            },
        ),
        migrations.CreateModel(
            name='EtapeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre de l'étape")),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'étape")),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', "En cours d'exécution"), ('COMPLETED', 'Terminé avec succès'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('TIMEOUT', 'Dépassement de temps')], default='PENDING', max_length=20, verbose_name="Statut d'exécution")),
                ('dateDebut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('dateFin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='audits.planaudit', verbose_name="Plan d'audit")),
            ],
            options={
                'verbose_name': "Étape d'Audit",
                'verbose_name_plural': "Étapes d'Audit",
                'ordering': ['ordre'],
            },
        ),
    ]
