# Generated by Django 6.1 on 2026-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='contexte',
            field=models.TextField(blank=True, default='', verbose_name="Description du contexte de l'audit"),
        ),
        migrations.AddField(
            model_name='audit',
            name='frequence',
            field=models.CharField(choices=[('AUCUNE', 'Aucune récurrence'), ('QUOTIDIEN', 'Quotidien (Toutes les 24h)'), ('HEBDOMADAIRE', 'Hebdomadaire (Toutes les semaines)'), ('MENSUEL', 'Mensuel (Tous les mois)')], default='AUCUNE', max_length=20, verbose_name='Fréquence de récurrence'),
        ),
        migrations.AddField(
            model_name='audit',
            name='prochaineExecution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prochaine exécution'),
        ),
        migrations.AddField(
            model_name='audit',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Titre de l'audit"),
        ),
        migrations.AddField(
            model_name='audit',
            name='typePlanification',
            field=models.CharField(choices=[('UNIQUE', 'Planification Unique (Ponctuelle)'), ('REPETITIVE', 'Planification Répétitive (Récurrente)')], default='UNIQUE', max_length=20, verbose_name='Type de planification'),
        ),
    ]
