# Generated by Django 6.1 on 2026-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_audit_contexte_audit_frequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='heureExecution',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'exécution programmée"),
        ),
        migrations.AddField(
            model_name='audit',
            name='webhookN8nUrl',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL Trigger Webhook n8n'),
        ),
    ]
