# Generated by Django 6.1 on 2026-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_audit_heureexecution_audit_webhookn8nurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='dateDernierLancement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier lancement'),
        ),
    ]
