# Generated by Django 6.1 on 2026-09-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_audit_datedernierlancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='resultatBrutN8n',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Résultats bruts reçus de n8n'),
        ),
    ]
