# Generated by Django 6.1 on 2026-09-04 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_audit_resultatbrutn8n'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateExecution', models.DateTimeField(auto_now_add=True, verbose_name="Date & Heure d'exécution")),
                ('dateFin', models.DateTimeField(blank=True, null=True, verbose_name='Date & Heure de fin')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PLANIFICATION', 'Planification'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('PARTIEL', 'Terminé partiellement'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20, verbose_name="Statut de l'exécution")),
                ('scoreSecurite', models.FloatField(default=0.0, verbose_name='Score de sécurité (0 à 100)')),
                ('resultatBrutN8n', models.JSONField(blank=True, default=dict, null=True, verbose_name='Résultats bruts n8n')),
                ('rapportText', models.TextField(blank=True, default='', verbose_name="Rapport d'analyse texte")),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='audits.audit', verbose_name='Audit parent')),
            ],
            options={
                'verbose_name': "Exécution d'Audit",
                'verbose_name_plural': "Exécutions d'Audit",
                'ordering': ['-dateExecution'],
            },
        ),
    ]
