# Generated by Django 6.1 on 2026-09-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_executionaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='emailsNotification',
            field=models.TextField(blank=True, default='', verbose_name='Adresses email de notification (séparées par des virgules)'),
        ),
    ]
