# Generated by Django 6.1 on 2026-08-15 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('vulns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du rapport')),
                ('format', models.CharField(choices=[('PDF', 'Document PDF (.pdf)'), ('HTML', 'Page Web HTML (.html)'), ('JSON', 'Fichier structuré JSON (.json)'), ('CSV', 'Fichier tabulaire CSV (.csv)')], default='HTML', max_length=10, verbose_name="Format d'export")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_REVISION', 'En révision'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=20, verbose_name='Statut du rapport')),
                ('cheminFichier', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemin du fichier généré')),
                ('scoreFinal', models.FloatField(default=0.0, verbose_name='Score de sécurité final (0 à 100)')),
                ('dateGeneration', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='audits.audit', verbose_name="Audit d'origine")),
                ('vulnerabilites', models.ManyToManyField(blank=True, related_name='rapports', to='vulns.vulnerabilite', verbose_name='Vulnérabilités incluses')),
            ],
            options={
                'verbose_name': "Rapport d'Évaluation",
                'verbose_name_plural': "Rapports d'Évaluation",
                'ordering': ['-dateGeneration'],
            },
        ),
    ]
