# Generated by Django 6.1 on 2026-08-15 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255, verbose_name='Action effectuée')),
                ('ressource', models.CharField(max_length=255, verbose_name='Ressource ciblée')),
                ('details', models.TextField(blank=True, default='', verbose_name='Détails techniques')),
                ('adresseIP', models.CharField(default='127.0.0.1', max_length=45, verbose_name='Adresse IP')),
                ('dateAction', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_activite', to='audits.audit', verbose_name='Audit concerné')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_activite', to='projects.projet', verbose_name='Projet concerné')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_activite', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur initiateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-dateAction'],
            },
        ),
    ]
