# Generated by Django 6.1 on 2026-08-15 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SLACK', 'Slack Webhook'), ('TELEGRAM', 'Telegram Bot'), ('DISCORD', 'Discord Webhook')], default='EMAIL', max_length=20, verbose_name='Canal de notification')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet / Titre')),
                ('message', models.TextField(verbose_name='Contenu du message')),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=20, verbose_name="Statut de l'envoi")),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('dateEnvoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi effectif")),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='audits.audit', verbose_name='Audit associé')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-dateCreation'],
            },
        ),
    ]
